name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [
  { pattern = "inconigto-mode.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.inconigto-mode.web.id", custom_domain = true },
  { pattern = "df.game.naver.com.inconigto-mode.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.inconigto-mode.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.inconigto-mode.web.id", custom_domain = true },
  { pattern = "support.zoom.us.inconigto-mode.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.inconigto-mode.web.id", custom_domain = true },

  { pattern = "inconigto.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.inconigto.biz.id", custom_domain = true },
  { pattern = "df.game.naver.com.inconigto.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.inconigto.biz.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.inconigto.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.inconigto.biz.id", custom_domain = true },
  { pattern = "cache.netflix.com.inconigto.biz.id", custom_domain = true },

  { pattern = "inconigto.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.inconigto.web.id", custom_domain = true },
  { pattern = "df.game.naver.com.inconigto.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.inconigto.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.inconigto.web.id", custom_domain = true },
  { pattern = "support.zoom.us.inconigto.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.inconigto.web.id", custom_domain = true },
]


[[kv_namespaces]]
binding = "SIREN"
id = "f7a1c12a83d349bb8e8868e7d524ac4c"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/inconigto-vpn/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/inconigto-vpn/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/inconigto-vpn/refs/heads/master/web/link.html"
